# Generated by Notifykit.
#
# Create a notifications table for managing emails and site notifications.
class CreateNotifications < ActiveRecord::Migration
  def self.up
    create_table :notifications do |t|
      t.string :kind
      t.string :token
      t.integer :user_id
      t.datetime :read_at
      t.datetime :clicked_at
      t.datetime :ignored_at
      t.datetime :cancelled_at
      t.datetime :email_sent_at
      t.datetime :email_not_sent_at
      t.string :email_not_sent_reason
      t.text :email_urls
      t.text :email_text
      t.text :email_html
      t.integer :click_count, default: 0
      t.integer :read_count, default: 0
      t.text :data
      t.integer :subject_id
      t.integer :subject_type

      t.timestamps
    end

    add_index :notifications, :created_at
    add_index :notifications, [:id, :created_at, :read_at, :clicked_at, :ignored_at, :cancelled_at], named: 'recent'
    add_index :notifications, :kind_id
    add_index :notifications, :user_id
  end

  def self.down
    drop_table :notifications
  end
end

