# Generated by Notifykit.
#
# Create a messages table for managing message templates for site notifications.
class CreateMessages < ActiveRecord::Migration
  def self.up
    create_table :messages do |t|
      t.string :name
      t.string :kind
      t.string :category
      t.boolean :promotional, default: false
      t.boolean :transactional, default: false
      t.boolean :do_not_track, default: false
      t.boolean :deliver_via_site, default: true
      t.boolean :deliver_via_email, default: true
      t.boolean :use_default_layout, default: true
      t.text :html_body
      t.text :text_body
      t.text :subject
      t.string :from
      t.string :bcc
      t.string :reply_to
      t.string :format

      t.timestamps
    end

    add_index :messages, :name
  end

  def self.down
    drop_table :messages
  end
end

